
services:
  backend:
    image: ghcr.io/ahmetdemirellisu/strategic-planning-application/backend:latest
    container_name: spu-backend
    environment:
      # İç ağda 'db' servis ismini kullanarak bağlanır
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET:-change-me-very-secret}
      JWT_EXPIRES_IN: 1d
      JWT_REFRESH_EXPIRES_IN: 7d
      # Frontend'in dışarıdan erişildiği URL
      CLIENT_URL: https://student-projects.sabanciuniv.edu/spu
    ports:
      - "9001:9001" # Dışarıdan 9003, içeride 3000
    networks:
      - spu-network

  frontend:
    image: ghcr.io/ahmetdemirellisu/strategic-planning-application/frontend:latest
    container_name: spu_frontend
    environment:
      # Frontend'in API'ye gitmesi gereken adres
      REACT_APP_API_URL: https://student-projects.sabanciuniv.edu/spu-api
    ports:
      - "8001:80" 
    networks:
      - spu-network

networks:
  spu-network:
    driver: bridge
